version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: saas_postgres
    restart: always
    environment:
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

  redis:
    image: redis:7-alpine
    container_name: saas_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - saas_network

volumes:
  postgres_data:

networks:
  saas_network:
    driver: bridge
